[tool.poetry]
name = "multidrop"
version = "1.1.0"
description = "A SiLA 2 connector for the Thermo Fisher Multidrop Reagent Dispenser, extended with USB support by DALSA-Lab."
authors = ["UniteLabs AG <developers+connector@unitelabs.ch>"]
maintainers = ["Kevin Skytte <s200539@dtu.dk>"]
readme = "README.md"
packages = [{ include = "connector", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
unitelabs-cdk = {version = "^0.2.2", source = "unitelabs"}
# unitelabs-bus = {git = "https://gitlab.com/unitelabs/cdk/python-bus.git", branch = "story/BUS-8_windows-serial-transport",  extras = ["serial"]}
unitelabs-bus = {version = "^0.1.6", source = "unitelabs", extras = ["serial"]}
mock-serial = "^0.0.1"
pyusb = "^1.3.1"

[tool.poetry.group.dev.dependencies]
black = "24.1.1"
cryptography = "41.0.2"
isort = "5.13.2"
pylint = "3.0.3"
pytest = "8.0.0"
pytest-asyncio = "0.23.5"
pytest-cov = "4.1.0"

[[tool.poetry.source]]
name = "unitelabs"
url = "https://gitlab.com/api/v4/groups/1009252/-/packages/pypi/simple"
priority = "supplemental"

[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
line_length = 120
profile = "black"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.messages_control]
disable = ["missing-module-docstring"]

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
